-- 코드를 입력하세요
SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS I JOIN REST_REVIEW AS R
ON R.REST_ID = I.REST_ID
WHERE SUBSTR(ADDRESS,1,2)='서울'
GROUP BY REST_ID
ORDER BY SCORE DESC